"""Initial migration with all current models

Revision ID: 264d2d80d3c5
Revises: 
Create Date: 2025-08-07 11:52:10.626601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264d2d80d3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('location_notes', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opening_cash', sa.Float(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('closing_cash', sa.Float(), nullable=True),
    sa.Column('expected_cash', sa.Float(), nullable=True),
    sa.Column('cash_diff', sa.Float(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('cash_breakdown', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('business_day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('business_day')
    # ### end Alembic commands ###
