"""Add other_income and discounts fields for POS features

Revision ID: 545ad61c1e74
Revises: 5b4f27ca902e
Create Date: 2025-08-14 00:32:39.503042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545ad61c1e74'
down_revision = '5b4f27ca902e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_income', sa.Float(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('discounts')

    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.drop_column('other_income')

    # ### end Alembic commands ###
