"""Add DailySettlement model

Revision ID: 5a5eea920c97
Revises: ba2a9d17662d
Create Date: 2025-09-01 23:55:51.386715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5eea920c97'
down_revision = 'ba2a9d17662d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_deposit', sa.Float(), nullable=True),
    sa.Column('total_next_day_opening_cash', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_settlement'))
    )
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_settlement_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_settlement_date'))

    op.drop_table('daily_settlement')
    # ### end Alembic commands ###
