"""Add remarks to DailySettlement model

Revision ID: 5abffb2591b9
Revises: 5a5eea920c97
Create Date: 2025-09-02 00:12:28.579663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abffb2591b9'
down_revision = '5a5eea920c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
