"""Add SystemSetting model

Revision ID: 5b4f27ca902e
Revises: ad17abff2eeb
Create Date: 2025-08-13 18:20:40.205173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4f27ca902e'
down_revision = 'ad17abff2eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_setting'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_setting')
    # ### end Alembic commands ###
