"""Remove old income columns and add other_income category type

Revision ID: 5ec6cc41880f
Revises: 22d1e8b77d0b
Create Date: 2025-09-14 11:35:07.896331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec6cc41880f'
down_revision = '22d1e8b77d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.drop_column('donation_total')
        batch_op.drop_column('other_total')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_total', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('donation_total', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
