"""Add signature fields

Revision ID: 8087f6ad07e1
Revises: f449746ec36c
Create Date: 2025-08-12 23:11:41.760085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8087f6ad07e1'
down_revision = 'f449746ec36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_operator', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_reviewer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_cashier', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.drop_column('signature_cashier')
        batch_op.drop_column('signature_reviewer')
        batch_op.drop_column('signature_operator')

    # ### end Alembic commands ###
