"""Add cash_received and change_given to Transaction model

Revision ID: 9823acd54d67
Revises: 5abffb2591b9
Create Date: 2025-09-03 12:59:58.080002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9823acd54d67'
down_revision = '5abffb2591b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_daily_settlement')
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_settlement_date'))
        batch_op.create_unique_constraint(batch_op.f('uq_daily_settlement_date'), ['date'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('change_given', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('change_given')
        batch_op.drop_column('cash_received')

    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_daily_settlement_date'), type_='unique')
        batch_op.create_index(batch_op.f('ix_daily_settlement_date'), ['date'], unique=1)

    op.create_table('_alembic_tmp_daily_settlement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_deposit', sa.FLOAT(), nullable=True),
    sa.Column('total_next_day_opening_cash', sa.FLOAT(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_settlement')),
    sa.UniqueConstraint('date', name=op.f('uq_daily_settlement_date'))
    )
    # ### end Alembic commands ###
