"""Add next_day_opening_cash to BusinessDay

Revision ID: ba2a9d17662d
Revises: e8ee5db0cf81
Create Date: 2025-09-01 22:59:22.715570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2a9d17662d'
down_revision = 'e8ee5db0cf81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_day_opening_cash', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.drop_column('next_day_opening_cash')

    # ### end Alembic commands ###
