"""empty message

Revision ID: d98f8b23f0ee
Revises: 545ad61c1e74
Create Date: 2025-08-20 00:14:32.159275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98f8b23f0ee'
down_revision = '545ad61c1e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_category_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('transaction_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_item_category_id_category')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transaction_item_transaction_id_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_item'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('discounts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounts', sa.TEXT(), nullable=True))

    op.drop_table('transaction_item')
    op.drop_table('category')
    # ### end Alembic commands ###
