"""Update SystemSetting table to use id as primary key

Revision ID: dd70343162cb
Revises: b3892bfeb63e
Create Date: 2025-09-23 16:48:31.123608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd70343162cb'
down_revision = 'b3892bfeb63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('discounts')

    # ### end Alembic commands ###
