"""Add flexible discount rules to Category model

Revision ID: e8ee5db0cf81
Revises: e8fecab650d7
Create Date: 2025-08-26 13:10:59.139651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ee5db0cf81'
down_revision = 'e8fecab650d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_business_day')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', sa.String(length=30), server_default='product', nullable=False))
        batch_op.add_column(sa.Column('discount_rules', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('discount_rules')
        batch_op.drop_column('category_type')

    op.create_table('_alembic_tmp_business_day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donation_total', sa.FLOAT(), nullable=True),
    sa.Column('other_total', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('location_notes', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('opening_cash', sa.FLOAT(), nullable=False),
    sa.Column('total_sales', sa.FLOAT(), nullable=True),
    sa.Column('closing_cash', sa.FLOAT(), nullable=True),
    sa.Column('expected_cash', sa.FLOAT(), nullable=True),
    sa.Column('cash_diff', sa.FLOAT(), nullable=True),
    sa.Column('total_items', sa.INTEGER(), nullable=True),
    sa.Column('total_transactions', sa.INTEGER(), nullable=True),
    sa.Column('cash_breakdown', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('signature_operator', sa.TEXT(), nullable=True),
    sa.Column('signature_reviewer', sa.TEXT(), nullable=True),
    sa.Column('signature_cashier', sa.TEXT(), nullable=True),
    sa.Column('location__id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['location__id'], ['location.id'], name=op.f('fk_business_day_location__id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_day'))
    )
    # ### end Alembic commands ###
