"""Add donation and other income fields to BusinessDay

Revision ID: e8fecab650d7
Revises: d98f8b23f0ee
Create Date: 2025-08-20 02:41:26.137097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fecab650d7'
down_revision = 'd98f8b23f0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_total', sa.Float(), nullable=True))
        batch_op.drop_column('other_income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_income', sa.FLOAT(), nullable=True))
        batch_op.drop_column('other_total')
        batch_op.drop_column('donation_total')

    # ### end Alembic commands ###
